model:
  class_path: models.nnUNetv2.model.nnUNetv2
  init_args:
    in_channels: 3
    num_classes: 1
    base_channels: 32
    depth: 5
    lr: 1e-3
    weight_decay: 1e-5
    use_pretrained: true
    use_attention: false 