model:
  class_path: models.NNUNetStyle.model.NNUNetStyle
  init_args:
    bce_loss_weight: 0.4
    false_negative_penalty: 0.01  # Final false negative penalty value
    false_negative_penalty_scheduler:
      enabled: true
      start_value: 0.0001  # Starting penalty value
      end_value: 0.01    # Final penalty value after warmup
      warmup_epochs: 60  # Number of epochs to reach end_value
      schedule_type: "linear"  # "linear" or "exponential"
    patient_weight: 0.5  # Weight multiplier for patient images (higher = more focus on tumors)
    control_weight: 0.5  # Weight multiplier for control images (lower = less focus on empty masks)
    # Not implemente yet
    # base_channels: 64
    # depth: 8
    dropout_rate: 0.1  # Dropout rate for regularization

