model:
  class_path: models.NNUNetV2Style.model.NNUNetV2Style
  init_args:
    bce_loss_weight: 0.4
    false_negative_penalty: 0.01  # Final false negative penalty value
    false_negative_penalty_scheduler:
      enabled: true
      start_value: 0.0001  # Starting penalty value
      end_value: 0.01    # Final penalty value after warmup
      warmup_epochs: 60  # Number of epochs to reach end_value
      schedule_type: "linear"  # "linear" or "exponential"
    patient_weight: 0.5  # Weight multiplier for patient images (higher = more focus on tumors)
    control_weight: 0.5  # Weight multiplier for control images (lower = less focus on empty masks)
    # nnUNet v2 specific parameters (REQUIRED)
    model_folder: "/path/to/nnunetv2/model"  # Path to nnUNet v2 model folder (REQUIRED)
    configuration_name: "2d_fullres"  # nnUNet v2 configuration name
    use_folds: null  # Folds to use (null = auto-detect)
    checkpoint_name: "checkpoint_final.pth"  # Checkpoint filename
    use_mirroring: true  # Use test time augmentation
    tile_step_size: 0.5  # Tile step size for inference 