model:
  class_path: models.AttentionUNet.model.AttentionUNet
  init_args:
    bce_loss_weight: 0.5
    lr: 1e-3
    weight_decay: 1e-3
    use_self_attention: true
    use_attention_gates: true
    # Aggressive memory optimization parameters
    base_channels: 12  # Further reduced for maximum memory efficiency
    attention_reduction_ratio: 32  # Much higher reduction ratio 