model:
  class_path: models.SimpleSwin.model.SimpleSwin
  init_args:
    in_channels: 1
    num_classes: 1
    lr: 1e-4
    weight_decay: 1e-5
    use_pretrained: true
    # model_name: "swin_base_patch4_window7_224"  # Options: swin_tiny, swin_small, swin_base
    model_name: "swinv2_base_window8_256.ms_in1k"