model:
  class_path: models.SimpleSwin.model.SimpleSwin
  init_args:
    bce_loss_weight: 0.4
    model_name: "swinv2_base_window8_256.ms_in1k"

# data:
#   class_path: data.data_default.TumorSegmentationDataModule
#   init_args:
#     val_split: 0.2
#     batch_size: 16
#     num_workers: 0
#     patient_control_ratio: 0.80
#     use_oversampling: False